const types = {
  MARK_MOVE: 'MARK_MOVE',
  USER_ADDED: 'USER_ADDED',
  TASK_ADD : 'TASK_ADD',
  TASK_COMPLETE : 'TASK_COMPLETE',
  TASK_INCOMPLETE: 'TASK_INCOMPLETE',
  TASK_REMOVE:'TASK_REMOVE',
};
export default types;